- name: Download and Install RPMs
  hosts: bigips
  any_errors_fatal: false
  vars:
    f5app_services_package_server: "{{ inventory_hostname }}"
    f5app_services_package_user: admin
    f5app_services_package_server_port: 443
    f5app_services_package_password: admin
    f5app_services_package_validate_certs: false
    f5app_services_package_transport: rest
    f5app_services_package_state: "present"

  tasks:
    - name: Download and Install AS3 RPM
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_url: "https://github.com/F5Networks/f5-appsvcs-extension/raw/master/dist/latest/f5-appsvcs-3.13.0-3.noarch.rpm"
        f5app_services_package_destination: "/tmp/f5-appsvcs-3.13.0-3.noarch.rpm"
        f5app_services_package_path: "/tmp/f5-appsvcs-3.13.0-3.noarch.rpm"
        f5app_services_package_checksum_url: "https://github.com/F5Networks/f5-appsvcs-extension/raw/master/dist/latest/f5-appsvcs-3.13.0-3.noarch.rpm.sha256"

    - name: Download and Install DO RPM
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_url: "https://github.com/F5Networks/f5-declarative-onboarding/raw/master/dist/f5-declarative-onboarding-1.6.0-1.noarch.rpm"
        f5app_services_package_checksum_url: "https://github.com/F5Networks/f5-declarative-onboarding/raw/master/dist/f5-declarative-onboarding-1.6.0-1.noarch.rpm.sha256"
        f5app_services_package_destination: "/tmp/f5-declarative-onboarding-1.6.0-1.noarch.rpm"
        f5app_services_package_path: "/tmp/f5-declarative-onboarding-1.6.0-1.noarch.rpm"

    - name: Download and Install TS RPM
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_url: "https://github.com/F5Networks/f5-telemetry-streaming/raw/master/dist/f5-telemetry-1.5.0-1.noarch.rpm"
        f5app_services_package_destination: "/tmp/f5-telemetry-1.5.0-1.noarch.rpm"
        f5app_services_package_checksum_url: "https://github.com/F5Networks/f5-telemetry-streaming/raw/master/dist/f5-telemetry-1.5.0-1.noarch.rpm.sha256"
        f5app_services_package_path: "/tmp/f5-telemetry-1.5.0-1.noarch.rpm"
